---
title: "NotreDameGiving"
author: "Imogen Meers"
date: "`r Sys.Date()`"
output: html_document
---

## Data & Cleaning
```{r}
new_portfolio = read.csv("New Portfolio.csv")
summary(new_portfolio)
```

```{r, message = FALSE, warning = FALSE}
library(dplyr)
old_portfolio = read.csv("Old Portfolio.csv")

# cleaning
# Char --> Date
cols1_2y <- c("Most.Recent.UNR.Gift.Date", "Sorin...Renewal.Date", "Rockne...Renewal.Date", "Law...Renewal.Date", "Grad.Bus...Renewal.Date")
cols1_4y <- c("Most.Recent.Visit.Date")

old_portfolio[cols1_2y] <- lapply(old_portfolio[cols1_2y], function(x) as.Date(x, format = "%m/%d/%y"))
old_portfolio[cols1_2y] <- lapply(old_portfolio[cols1_4y], function(x) as.Date(x, format = "%m/%d/%Y"))

old_portfolio$Last.Gift.Days.Ago = as.numeric(Sys.Date() - old_portfolio$Most.Recent.UNR.Gift.Date)

# Take out $ at start --> numeric
cols2 <- c("Most.Recent.UNR.Gift.Legal.Amount", "Most.Recent.UNR.Gift.Credit.Amount", "Capacity.Rating...Rating.Low.Amount.Dim", "Lifetime.Production.Household.Extended.Amount", "Current.Campaign.Production.Household.Extended.Amount", "Sorin...Current.Year..", "Sorin...One.Year.Prior..", "Rockne...Current.Year..", "Rockne...One.Year.Prior..", "Law...Current.Year..", "Law...One.Year.Prior..", "Grad.Bus...Current.Year..", "Grad.Bus...One.Year.Prior..", "X2025.FY.Matching.Gifts", "X2024.FY.Matching.Gifts", "X2025.FY.Total.Unrestricted.Gifts", "X2024.FY.Total.Unrestricted.Gifts", "X2023.FY.Total.Unrestricted.Gifts", "X2022.FY.Total.Unrestricted.Gifts", "X2021.FY.Total.Unrestricted.Gifts")
old_portfolio[cols2] <- lapply(old_portfolio[cols2], function(x) as.numeric(gsub("[$,]", "", x)))

old_portfolio$Zip.Code <- as.numeric(old_portfolio$Zip.Code)

# Y/N to 1/0
cols3 <- c("X70.5..Ind", "Has.Spouse.Indicator", "Participation.Donor.Current.Fiscal.Year", "Current.Parent.Ind", "Monogram...Big.4", "Monogram...Non.Big.4", "Dual.Domer.Household")
old_portfolio[cols3] <- lapply(old_portfolio[cols3], function(x) ifelse(x == "Y", 1, ifelse(x == "N", 0, NA)))

old_portfolio <- old_portfolio %>%
  mutate(General.Active.Giving.Society = sub("^(\\S+).*", "\\1", Active.Giving.Society.Affiliation.List),
         General.Gift.Designation = sub("^(\\S+).*", "\\1", Most.Recent.UNR.Gift.Designation))

# Region
old_portfolio$Region <- dplyr::case_when(
  old_portfolio$Preferred.Address...State.Code %in% c("WA", "OR", "ID", "MT", "WY", "AK") ~ "Northwest",
  old_portfolio$Preferred.Address...State.Code %in% c("CA", "NV", "AZ", "NM", "UT", "CO") ~ "Southwest",
  old_portfolio$Preferred.Address...State.Code == "IL" ~ "Illinois",
  old_portfolio$Preferred.Address...State.Code %in% c("TX", "FL", "GA", "NC", "SC", "AL", "TN", "LA", "MS", "KY", "OK", "AR") 
  ~ "Southern",
  old_portfolio$Preferred.Address...State.Code %in% c("OH", "MI", "IN", "WI", "MO", "IA", "KS", "NE", "MN", "ND", "SD") 
  ~ "Central",
  old_portfolio$Preferred.Address...State.Code %in% c("NY", "NJ", "CT") ~ "NY Metro",
  old_portfolio$Preferred.Address...State.Code %in% c("PA", "MA", "MD", "VA", "DE", "RI", "NH", "VT", "ME", "DC") 
  ~ "East Coast",
  TRUE ~ "Other")

# Age Group
old_portfolio$Age.Group <- cut(
  old_portfolio$Age,
  breaks = c(-Inf, 17, 22, 34, 44, 59, 75, Inf),
  labels = c("<18", "18–22", "23–34", "35–44", "45–59", "60–75", "75+"),
  right = TRUE
)

summary(old_portfolio)
```

Correlation
```{r}
library(ggplot2)
library(reshape2)
library(dplyr)

nums <- old_portfolio %>% select(where(is.numeric)) %>% select(-ID.Number, -Household.ID, -X70.5..Ind)
cor_matrix <- cor(nums, use = "complete.obs")

cor_matrix_melted <- melt(cor_matrix)
ggplot(cor_matrix_melted, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 5),
        axis.text.y = element_text(size = 5))
```

## Exploratory
Gift amount by region
```{r}
old_portfolio %>% group_by(Region) %>%
  summarize(n_people = length(unique(ID.Number)),
            total_gifts_amount = sum(Lifetime.Production.Household.Extended.Amount),
            avg_gift_amount = mean(Most.Recent.UNR.Gift.Legal.Amount, na.rm = TRUE))
```

Gift amount by state
```{r}
old_portfolio %>% group_by(Preferred.Address...State.Code) %>%
  summarize(n_people = length(unique(ID.Number)),
            total_gifts_amount = sum(Lifetime.Production.Household.Extended.Amount),
            avg_gift_amount = mean(Most.Recent.UNR.Gift.Legal.Amount, na.rm = TRUE))
```

Gift amount by society
```{r}
old_portfolio %>% group_by(Active.Giving.Society.Affiliation.List) %>%
  summarize(n_people = length(unique(ID.Number)),
            total_gifts_amount = sum(Lifetime.Production.Household.Extended.Amount),
            avg_gift_amount = mean(Most.Recent.UNR.Gift.Legal.Amount, na.rm = TRUE))
```

Gift amount by month of gift
```{r, message = FALSE}
library(lubridate)
monthly <- old_portfolio %>% 
  mutate(month = month(Most.Recent.UNR.Gift.Date)) %>%
  group_by(month) %>%
  summarize(n_people = length(unique(ID.Number)),
            total_gifts_amount = sum(Lifetime.Production.Household.Extended.Amount),
            avg_gift_amount = mean(Most.Recent.UNR.Gift.Legal.Amount, na.rm = TRUE)) %>%
  filter(!is.na(month))

ggplot(monthly, aes(x = month)) +
  geom_point(aes(y = total_gifts_amount, color = "total_gifts_amount")) +
  geom_line(aes(y = total_gifts_amount, color = "total_gifts_amount")) +
  geom_point(aes(y = avg_gift_amount*10000, color = "avg_gift_amount")) +
  geom_line(aes(y = avg_gift_amount*10000, color = "avg_gift_amount")) +
  scale_color_manual(values = c( "total_gifts_amount" = "purple", "avg_gift_amount" = "blue"),
    name = "Metric") +
  ggtitle("When Do People Donate?") + theme_minimal()
```

## Summary Stats
```{r, warning = FALSE}
# average age
avg_age <- mean(old_portfolio$Age, na.rm = TRUE)
avg_age
                
# where are donations going?
top10_donation_locs <- sort(table(old_portfolio$Most.Recent.UNR.Gift.Designation), decreasing = TRUE)[1:10]
top10_donation_locs

top10_donation_locs_amount <- old_portfolio %>%
  group_by(Most.Recent.UNR.Gift.Designation) %>%
  summarise(avg_given_2024 = mean(X2024.FY.Total.Unrestricted.Gifts, na.rm = TRUE)) %>%
  arrange(desc(avg_given_2024)) %>% slice_head(n = 10)
top10_donation_locs_amount


# top 10 locations (zip, state) --> in terms of count of donors
top10_zips <- sort(table(old_portfolio$Zip.Code), decreasing = TRUE)[1:10]
top10_zips
top10_states <- sort(table(old_portfolio$Preferred.Address...State.Code), decreasing = TRUE)[1:10]
top10_states

# <5, 5-10, 10-25, 25+ --> average amount given
groups <- old_portfolio %>%
  mutate(consecutive_year_group = case_when(
    Consecutive.Years < 5 ~ "<5",
    Consecutive.Years >= 5 & Consecutive.Years < 10 ~ "5-10",
    Consecutive.Years >= 10 & Consecutive.Years < 15 ~ "10-15",
    Consecutive.Years >= 15 & Consecutive.Years < 20 ~ "15-20",
    Consecutive.Years >= 20 ~ "20+"
  )) %>%
  group_by(consecutive_year_group) %>%
  summarise(avg_amount_2024 = mean(X2024.FY.Total.Unrestricted.Gifts, na.rm = TRUE)) %>%
  arrange(match(consecutive_year_group, c("<5", "5-10", "10-15", "15-20", "20+")))
groups

# what age do people typically start donating? (count by age group & amount)
age_counts <- old_portfolio %>%
  group_by(Age) %>% summarize(count = n(),
                              avg_donation_2024 = mean(X2024.FY.Total.Unrestricted.Gifts, na.rm = TRUE),
                              avg_donation_2023 = mean(X2023.FY.Total.Unrestricted.Gifts, na.rm = TRUE)) %>%
  filter(Age > 17)
ggplot(age_counts, aes(x = Age)) + 
  geom_line(aes(y = count, color = "# Donors")) + 
  geom_line(aes(y = avg_donation_2024, color = "Avg. UNR Gifts 2024")) + 
  geom_line(aes(y = avg_donation_2023, color = "Avg. UNR Gifts 2023")) + 
  scale_color_manual(values = c("# Donors" = "blue", "Avg. UNR Gifts 2024" = "purple")) +
  theme_minimal()
```


## Modeling
Outcome vars: total donation, increase in last three years, society membership (1/0)

Effect on Gift Amount over the Years
```{r}
library(tidyr)
gift_cols <- c("X2021.FY.Total.Unrestricted.Gifts", "X2022.FY.Total.Unrestricted.Gifts", "X2023.FY.Total.Unrestricted.Gifts", 
                  "X2024.FY.Total.Unrestricted.Gifts", "X2025.FY.Total.Unrestricted.Gifts")

long_data_gifts <- old_portfolio %>%
  gather(key = "Year", value = "Gift.Amount", all_of(gift_cols)) %>%
  mutate(Year = as.integer(gsub("X", "", gsub(".FY.Total.Unrestricted.Gifts", "", Year))))
```

```{r}
library(lme4)
library(lmerTest)

# scale
long_data_gifts_scaled <- long_data_gifts %>% select(-ID.Number, -Gift.Amount) %>% select(where(is.numeric)) %>% scale() %>% as.data.frame
non_numeric_data <- long_data_gifts %>% select(where(~ !is.numeric(.)))
long_data_gifts_scaled$ID.Number <- long_data_gifts$ID.Number
long_data_gifts_scaled$Gift.Amount <- long_data_gifts$Gift.Amount
long_data_gifts_scaled <- cbind(non_numeric_data, long_data_gifts_scaled)

model <- lmer(Gift.Amount ~ Age.Group + Age + Region + General.Gift.Designation + Consecutive.Years + General.Active.Giving.Society + Current.Parent.Ind + Monogram...Big.4 + Monogram...Non.Big.4 + Dual.Domer.Household + Last.Gift.Days.Ago + (1 | ID.Number), data = long_data_gifts_scaled)

summary(model)
```

```{r}
model_data <- model@frame
model_data$Predicted.Gift.Amount <- predict(model)


top_1000_by_region <- model_data %>%
  distinct(ID.Number, .keep_all = TRUE) %>%  
  group_by(Region) %>%
  arrange(desc(Predicted.Gift.Amount)) %>%
  slice_head(n = 1000) %>% 
  ungroup()
```

